"""Add foreign key to comment

Revision ID: 8e7bd01db13d
Revises: b739f587cc84
Create Date: 2025-07-13 11:41:26.447431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7bd01db13d'
down_revision = 'b739f587cc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
