"""Add foreign key to comments

Revision ID: b739f587cc84
Revises: 26b8a0253e29
Create Date: 2025-07-13 11:32:56.652121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b739f587cc84'
down_revision = '26b8a0253e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
